name: BuyBook Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
    vercel: 
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      steps:
        - uses: actions/checkout@v2
        - name: deploy site to vercel      
          uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.BUYBOOK_VERCEL }}
            vercel-args: '--prod'
            vercel-org-id: ${{ secrets.BUYBOOK_ORG_ID}}
            vercel-project-id: ${{ secrets.BUYBOOK_PROJ_ID}}