name: BuyBook Linter
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    types:
      - "opened"
    branches-ignore:
      - "main"
jobs:
  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci

      - name: Run linter
      - run: npm run lint