name: BuyBook Linter
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    types:
      - "opened"
    branches-ignore:
      - "main"
jobs:
  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run linter
        uses: github/super-linter@v4
    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      VALIDATE_ALL_CODEBASE: false
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
      VALIDATE_BASH: false
      VALIDATE_BASH_EXEC: false
      VALIDATE_SHELL_SHFMT: false
      VALIDATE_CSS: false
      VALIDATE_YAML: false